#!/usr/bin/env bash

# TODO
# -- Add more transmission opts

# Sample usage:
# ./tpbget [-a] [-d dir] https://thepiratebay.org/top/303

DEPENDENCIES="wget transmission-daemon transmission-remote"
for DEP in $DEPENDENCIES; do
	if [ -z "`which $DEP`" ]; then
		echo "ERROR: Missing dependency '$DEP'." >&2
		exit
	fi
done

while getopts "ad:" opt; do
	case $opt in
	a)
		auth=1
   		;;
	d)
		dir=$OPTARG
		;;
	\?)
		echo "invalid option: -$OPTARG" >&2
		exit 1
		;;
	esac
done

if [ -z "$dir" ]; then
	dir=.
fi

if [ -d "$dir" ]; then
	cd "$dir"
else
	echo "$dir doesn't seem to exist" >&2
	exit 1
fi

pageUrl=${!#}
if [ -z "$pageUrl" ]; then
	echo "Usage: $0 [-a] [-d dir] https://thepiratebay.org/top/303" >&2
	exit 1
fi

if [[ ! "$pageUrl" =~ ^https?:// ]]; then
	echo "Bad URL. Not HTTP?" >&2
	exit 1
fi

echo "Fetching the torrents... this might take a while"
wget -A ".torrent" -r $pageUrl -H "torrents.thepiratebay.org" --no-check-certificate -l1 -nH -nd -e robots=off -q
echo "Done fetching the torrents"

echo "Adding the torrents to transmission"

if [ -z "$auth" ]; then
	find . -name "*.torrent" -print0|xargs -0 transmission-remote -a
else
	echo "Username: "
	read user
	echo "Pass"
	read -s pass
	find . -name "*.torrent" -print0|xargs -0 transmission-remote -n$user:$pass -a
fi

echo "Done adding the torrents to transmission"